/*
 * generated by Xtext 2.12.0
 */
package tr.edu.metu.ceng.megamodel.hypomethod.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import tr.edu.metu.ceng.megamodel.hypomethod.ui.internal.HypomethodActivator;

public class HypoMethodUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return HypomethodActivator.getInstance().getInjector("tr.edu.metu.ceng.megamodel.hypomethod.HypoMethod");
	}

}
