/**
 * generated by Xtext 2.12.0
 */
package tr.edu.metu.ceng.megamodel.hypomethod.hypoMethod.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import tr.edu.metu.ceng.megamodel.hypomethod.hypoMethod.ExperimentOntology;
import tr.edu.metu.ceng.megamodel.hypomethod.hypoMethod.HypoMethodPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Experiment Ontology</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ExperimentOntologyImpl extends MinimalEObjectImpl.Container implements ExperimentOntology
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ExperimentOntologyImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return HypoMethodPackage.Literals.EXPERIMENT_ONTOLOGY;
  }

} //ExperimentOntologyImpl
