/**
 *
 * $Id$
 */
package tr.edu.metu.ceng.xperimenter.validation;

import org.eclipse.emf.common.util.EList;

import tr.edu.metu.ceng.xperimenter.Type;

/**
 * A sample validator interface for {@link tr.edu.metu.ceng.xperimenter.Model}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ModelValidator {
	boolean validate();

	boolean validateElements(EList<Type> value);
}
