/**
 *
 * $Id$
 */
package tr.edu.metu.ceng.xperimenter.validation;

import org.eclipse.emf.common.util.EList;

import tr.edu.metu.ceng.xperimenter.Port;
import tr.edu.metu.ceng.xperimenter.SimModelType;

/**
 * A sample validator interface for {@link tr.edu.metu.ceng.xperimenter.Simulation}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SimulationValidator {
	boolean validate();

	boolean validateModelFilePath(String value);
	boolean validateModelType(SimModelType value);
	boolean validatePorts(EList<Port> value);
}
