/**
 *
 * $Id$
 */
package tr.edu.metu.ceng.xperimenter.validation;

import tr.edu.metu.ceng.xperimenter.NumberGenerator;
import tr.edu.metu.ceng.xperimenter.VariableGroup;
import tr.edu.metu.ceng.xperimenter.VariableType;

/**
 * A sample validator interface for {@link tr.edu.metu.ceng.xperimenter.Variable}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface VariableValidator {
	boolean validate();

	boolean validateType(VariableType value);
	boolean validateGroup(VariableGroup value);
	boolean validateLowValue(int value);
	boolean validateHighValue(int value);
	boolean validateGenerator(NumberGenerator value);
}
