/**
 * generated by Xtext 2.12.0
 */
package tr.edu.metu.ceng.megamodel.hypomethod.hypoMethod;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Experiment Ontology</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see tr.edu.metu.ceng.megamodel.hypomethod.hypoMethod.HypoMethodPackage#getExperimentOntology()
 * @model
 * @generated
 */
public interface ExperimentOntology extends EObject
{
} // ExperimentOntology
