/**
 * generated by Xtext 2.12.0
 */
package tr.edu.metu.ceng.megamodel.hypomethod.hypoMethod;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Response</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link tr.edu.metu.ceng.megamodel.hypomethod.hypoMethod.Response#getResponseName <em>Response Name</em>}</li>
 *   <li>{@link tr.edu.metu.ceng.megamodel.hypomethod.hypoMethod.Response#getResponseType <em>Response Type</em>}</li>
 * </ul>
 *
 * @see tr.edu.metu.ceng.megamodel.hypomethod.hypoMethod.HypoMethodPackage#getResponse()
 * @model
 * @generated
 */
public interface Response extends EObject
{
  /**
   * Returns the value of the '<em><b>Response Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Response Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Response Name</em>' attribute.
   * @see #setResponseName(String)
   * @see tr.edu.metu.ceng.megamodel.hypomethod.hypoMethod.HypoMethodPackage#getResponse_ResponseName()
   * @model
   * @generated
   */
  String getResponseName();

  /**
   * Sets the value of the '{@link tr.edu.metu.ceng.megamodel.hypomethod.hypoMethod.Response#getResponseName <em>Response Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Response Name</em>' attribute.
   * @see #getResponseName()
   * @generated
   */
  void setResponseName(String value);

  /**
   * Returns the value of the '<em><b>Response Type</b></em>' attribute.
   * The literals are from the enumeration {@link tr.edu.metu.ceng.megamodel.hypomethod.hypoMethod.ResponseType}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Response Type</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Response Type</em>' attribute.
   * @see tr.edu.metu.ceng.megamodel.hypomethod.hypoMethod.ResponseType
   * @see #setResponseType(ResponseType)
   * @see tr.edu.metu.ceng.megamodel.hypomethod.hypoMethod.HypoMethodPackage#getResponse_ResponseType()
   * @model
   * @generated
   */
  ResponseType getResponseType();

  /**
   * Sets the value of the '{@link tr.edu.metu.ceng.megamodel.hypomethod.hypoMethod.Response#getResponseType <em>Response Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Response Type</em>' attribute.
   * @see tr.edu.metu.ceng.megamodel.hypomethod.hypoMethod.ResponseType
   * @see #getResponseType()
   * @generated
   */
  void setResponseType(ResponseType value);

} // Response
