/*
 * generated by Xtext 2.12.0
 */
package tr.edu.metu.ceng.megamodel.sedml


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class SedmlRuntimeModule extends AbstractSedmlRuntimeModule {
}
