/**
 * generated by Xtext 2.12.0
 */
package tr.edu.metu.ceng.megamodel.sedml.sedml.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import tr.edu.metu.ceng.megamodel.sedml.sedml.SedmlPackage;
import tr.edu.metu.ceng.megamodel.sedml.sedml.dataGenerator;
import tr.edu.metu.ceng.megamodel.sedml.sedml.listOfDataGenerators;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>list Of Data Generators</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link tr.edu.metu.ceng.megamodel.sedml.sedml.impl.listOfDataGeneratorsImpl#getDatagenerator <em>Datagenerator</em>}</li>
 * </ul>
 *
 * @generated
 */
public class listOfDataGeneratorsImpl extends MinimalEObjectImpl.Container implements listOfDataGenerators
{
  /**
   * The cached value of the '{@link #getDatagenerator() <em>Datagenerator</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDatagenerator()
   * @generated
   * @ordered
   */
  protected EList<dataGenerator> datagenerator;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected listOfDataGeneratorsImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SedmlPackage.Literals.LIST_OF_DATA_GENERATORS;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<dataGenerator> getDatagenerator()
  {
    if (datagenerator == null)
    {
      datagenerator = new EObjectContainmentEList<dataGenerator>(dataGenerator.class, this, SedmlPackage.LIST_OF_DATA_GENERATORS__DATAGENERATOR);
    }
    return datagenerator;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case SedmlPackage.LIST_OF_DATA_GENERATORS__DATAGENERATOR:
        return ((InternalEList<?>)getDatagenerator()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SedmlPackage.LIST_OF_DATA_GENERATORS__DATAGENERATOR:
        return getDatagenerator();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SedmlPackage.LIST_OF_DATA_GENERATORS__DATAGENERATOR:
        getDatagenerator().clear();
        getDatagenerator().addAll((Collection<? extends dataGenerator>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SedmlPackage.LIST_OF_DATA_GENERATORS__DATAGENERATOR:
        getDatagenerator().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SedmlPackage.LIST_OF_DATA_GENERATORS__DATAGENERATOR:
        return datagenerator != null && !datagenerator.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //listOfDataGeneratorsImpl
