/*
 * generated by Xtext 2.12.0
 */
package tr.edu.metu.ceng.megamodel.hypomethod.ide


/**
 * Use this class to register ide components.
 */
class HypoMethodIdeModule extends AbstractHypoMethodIdeModule {
}
