/*
 * generated by Xtext 2.12.0
 */
package tr.edu.metu.ceng.megamodel.hypomethod


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class HypoMethodStandaloneSetup extends HypoMethodStandaloneSetupGenerated {

	def static void doSetup() {
		new HypoMethodStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
