/**
 *
 * $Id$
 */
package sedml.validation;

import org.eclipse.emf.common.util.EList;

import sedml.plot2D;

/**
 * A sample validator interface for {@link sedml.listOfOutputs}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface listOfOutputsValidator {
	boolean validate();

	boolean validatePlot2D(EList<plot2D> value);
}
