/**
 *
 * $Id$
 */
package sedml.validation;

import sedml.listOfDataGenerators;
import sedml.listOfModels;
import sedml.listOfOutputs;
import sedml.listOfSimulations;
import sedml.listOfTasks;

/**
 * A sample validator interface for {@link sedml.sedML}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface sedMLValidator {
	boolean validate();

	boolean validateVersion(int value);
	boolean validateLevel(int value);
	boolean validateListOfSimulations(listOfSimulations value);
	boolean validateListOfModels(listOfModels value);
	boolean validateListOfTasks(listOfTasks value);
	boolean validateListOfDataGenerators(listOfDataGenerators value);
	boolean validateListOfOutputs(listOfOutputs value);
}
