/**
 *
 * $Id$
 */
package sedml.validation;

import sedml.model;
import sedml.uniformTimeCourse;

/**
 * A sample validator interface for {@link sedml.task}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface taskValidator {
	boolean validate();

	boolean validateId(String value);
	boolean validateModelReference(model value);
	boolean validateSimulationReference(uniformTimeCourse value);
	boolean validateName(String value);
}
