/**
 *
 * $Id$
 */
package sedml.validation;

import sedml.algorithm;

/**
 * A sample validator interface for {@link sedml.uniformTimeCourse}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface uniformTimeCourseValidator {
	boolean validate();

	boolean validateId(String value);
	boolean validateInitialTime(int value);
	boolean validateOutputStartTime(int value);
	boolean validateOutputEndTime(int value);
	boolean validateNumberOfPoints(int value);
	boolean validateAlgorithm(algorithm value);
}
