/**
 *
 * $Id$
 */
package sedml.validation;

import sedml.task;

/**
 * A sample validator interface for {@link sedml.variable}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface variableValidator {
	boolean validate();

	boolean validateId(String value);
	boolean validateTarget(String value);
	boolean validateTaskReference(task value);
	boolean validateSymbol(String value);
}
