<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="sedml" nsURI="http://www.ceng.metu.edu.tr/~e1774785/megamodel/sedml"
    nsPrefix="sedml">
  <eClassifiers xsi:type="ecore:EClass" name="sedML">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="level" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="listOfSimulations" eType="#//listOfSimulations"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="listOfModels" eType="#//listOfModels"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="listOfTasks" eType="#//listOfTasks"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="listOfDataGenerators" eType="#//listOfDataGenerators"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="listOfOutputs" eType="#//listOfOutputs"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="listOfModels">
    <eStructuralFeatures xsi:type="ecore:EReference" name="model" upperBound="-1"
        eType="#//model" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="model">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="language" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="source" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="listOfTasks">
    <eStructuralFeatures xsi:type="ecore:EReference" name="task" upperBound="-1" eType="#//task"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="task">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modelReference" eType="#//model"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="simulationReference" eType="#//uniformTimeCourse"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="listOfDataGenerators">
    <eStructuralFeatures xsi:type="ecore:EReference" name="datagenerator" upperBound="-1"
        eType="#//dataGenerator" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="dataGenerator">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="listOfVariables" eType="#//listOfVariables"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="math" eType="#//math" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="listOfVariables">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" upperBound="-1"
        eType="#//variable" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="variable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="target" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="taskReference" eType="#//task"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="symbol" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="math">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="xlms" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="listOfOutputs">
    <eStructuralFeatures xsi:type="ecore:EReference" name="plot2D" upperBound="-1"
        eType="#//plot2D" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="plot2D">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="listOfCurves" eType="#//listOfCurves"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="listOfCurves">
    <eStructuralFeatures xsi:type="ecore:EReference" name="curve" upperBound="-1"
        eType="#//curve" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="curve">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="logX" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="logY" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="xDataReference" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="yDataReference" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="listOfSimulations">
    <eStructuralFeatures xsi:type="ecore:EReference" name="uniformTimeCourse" upperBound="-1"
        eType="#//uniformTimeCourse" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="uniformTimeCourse">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="initialTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="outputStartTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="outputEndTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfPoints" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="algorithm" eType="#//algorithm"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="algorithm">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kisaoID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
