/*
 * generated by Xtext 2.12.0
 */
package tr.edu.metu.ceng.megamodel.hypomethod.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import tr.edu.metu.ceng.megamodel.hypomethod.parser.antlr.internal.InternalHypoMethodParser;
import tr.edu.metu.ceng.megamodel.hypomethod.services.HypoMethodGrammarAccess;

public class HypoMethodParser extends AbstractAntlrParser {

	@Inject
	private HypoMethodGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalHypoMethodParser createParser(XtextTokenStream stream) {
		return new InternalHypoMethodParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public HypoMethodGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(HypoMethodGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
