/*
 * generated by Xtext 2.12.0
 */
package tr.edu.metu.ceng.megamodel.hypomethod.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import tr.edu.metu.ceng.megamodel.hypomethod.ui.internal.HypomethodActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class HypoMethodExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return HypomethodActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return HypomethodActivator.getInstance().getInjector(HypomethodActivator.TR_EDU_METU_CENG_MEGAMODEL_HYPOMETHOD_HYPOMETHOD);
	}
	
}
